FROM node:22-alpine AS development

ARG HOST_UID=1000
ARG HOST_GID=1000
ARG HOST_USER=node
ARG HOST_GROUP=node
ARG APP_DIR=/app

# Создаем пользователя с таким же UID/GID как на хосте
RUN apk add --no-cache shadow && \
    groupmod -g $HOST_GID $HOST_GROUP && \
    usermod -u $HOST_UID -g $HOST_GID $HOST_GROUP

RUN apk update && apk upgrade
RUN apk add --no-cache git

WORKDIR $APP_DIR

# Копируем только package.json для кэширования слоя npm install
COPY ./app/package*.json ./

# Установка зависимостей с кэшированием
RUN npm install && \
    chown -R node:node $APP_DIR

USER node

EXPOSE 5173

CMD ["npm", "run", "dev"]