FROM node:22-alpine AS builder

WORKDIR /app

COPY ./app/package*.json ./
# Install exact deps for reproducible builds
RUN npm ci && npm cache clean --force

COPY ./app .
RUN npm run build

FROM nginx:stable-alpine AS production

COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]